language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update

script:
  - composer install --ignore-platform-reqs
  - if [ $(phpenv version-name) = "7.0" ] || [ $(phpenv version-name) = "7.1" ]; then vendor/bin/phing tests; fi
  - if [ $(phpenv version-name) != "7.0" ] && [ $(phpenv version-name) != "7.1" ]; then vendor/bin/phing tests:phpunit; fi

after_script:
  - php vendor/bin/coveralls -v
