language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
before_script:
  - composer self-update
script:
  - composer install --ignore-platform-reqs
  - vendor/bin/phing
after_script:
  - php vendor/bin/coveralls -v
